apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-postgui.fullname" . }}
  labels:
    {{- include "helm-postgui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "8771"
      port: {{ .Values.service.port }}
      targetPort: 8771
      nodePort: 30082
  selector:
    {{- include "helm-postgui.selectorLabels" . | nindent 4 }}
